# Generated by Django 2.2.3 on 2019-08-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190818_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(blank=True, choices=[('cachorro', 'cachorro'), ('gato', 'gato'), ('pássaro', 'pássaro'), ('roedor', 'roedor'), ('cavalo', 'cavalo'), ('outros', 'outros')], max_length=200, null=True, verbose_name='Pet type'),
        ),
    ]
